INSERT INTO users (name, age) VALUES ('Albus', 113);
INSERT INTO users (name, age) VALUES ('Alex', 33);
INSERT INTO users (name, age) VALUES ('Amanda', 24);
INSERT INTO users (name, age) VALUES ('Bear', 6);
INSERT INTO users (name, age) VALUES ('Ena', 24);
INSERT INTO users (name, age) VALUES ('Finnebar', 17);
INSERT INTO users (name, age) VALUES ('Franz', 100);
INSERT INTO users (name, age) VALUES ('Hermione', 30);
INSERT INTO users (name, age) VALUES ('Iguana', 4);
INSERT INTO users (name, age) VALUES ('Katie', 24);
INSERT INTO users (name, age) VALUES ('Marissa', 24);
INSERT INTO users (name, age) VALUES ('Pacha', 5);
INSERT INTO users (name, age) VALUES ('Rosey', 9);
INSERT INTO users (name, age) VALUES ('Sirius', 36);
INSERT INTO users (name, age) VALUES ('Sophie', 24);
INSERT INTO users (name, age) VALUES ('Squid', 5);
INSERT INTO users (name, age) VALUES ('Swizzle', 4);
INSERT INTO users (name, age) VALUES ('Victoria', 23);
INSERT INTO users (name, age) VALUES ('Voldemort', 90);
INSERT INTO users (name, age) VALUES ('Whale', 6);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('addition', 'house', 100, 2020-01-01, 2020-01-02);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('garage', 'house', 100, 2020-01-01, 2020-01-02);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('den', 'house', 100, 2020-01-01, 2020-01-02);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('living_room', 'house', 100, 2020-01-01, 2020-01-02);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('family_room', 'house', 100, 2020-01-01, 2020-01-02);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('bedroom1', 'house', 100, 2020-01-01, 2020-01-02);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('bedroom2', 'house', 100, 2020-01-01, 2020-01-02);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('master_bedroom', 'house', 100, 2020-01-01, 2020-01-02);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('bathroom', 'house', 100, 2020-01-01, 2020-01-02);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('half_bath', 'house', 100, 2020-01-01, 2020-01-02);

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3,11);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3,12);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3,13);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3,14);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3,15);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3,16);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3,17);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4,18);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4,19);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 5,20);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6,4);


